<script lang="ts">
  import { t } from "../../lib/i18n/index.svelte";
  import { dealsApi, type DealContext, type DealAttachment } from "./api";
  import AttachmentChips from "../../components/AttachmentChips.svelte";
  import { dealsStore } from "./store.svelte";
  let {company,onthread,onevent,onsearch}: {company:string;onthread:(id:number,messageId?:number)=>void;onevent:(id:number,startTs:number)=>void;onsearch:(query:string)=>void}=$props();
  let context=$state<DealContext|null>(null), notes=$state(""), loading=$state(false), saving=$state(false), error=$state(""), saved=$state(false), tab=$state("conversations");
  let currentCompany="", generation=0;
  const dirty=$derived(context!==null && notes!==context.notes);
  async function load(name:string){const request=++generation;loading=true;error="";try{const result=await dealsApi.context(name);if(request!==generation)return;context=result;notes=dealsStore.noteDraft(name)??result.notes;currentCompany=name;}catch(e){if(request===generation)error=String((e as {message?:string})?.message??e);}finally{if(request===generation)loading=false;}}
  $effect(()=>{const name=company;void dealsStore.revision;if(name!==currentCompany){context=null;notes="";tab="conversations";saved=false;}void load(name);});
  async function save(pin:number|null,includeNotes:boolean){if(!context||saving)return;saving=true;error="";try{await dealsStore.saveContext(company,includeNotes?notes:context.notes,pin);saved=includeNotes;if(includeNotes)dealsStore.clearNoteDraft(company);await load(company);}catch(e){error=String((e as {message?:string})?.message??e);}finally{saving=false;}}
  function when(ts:number,allDay=false){return new Date(ts*1000).toLocaleString(undefined,allDay?{weekday:"short",month:"short",day:"numeric",timeZone:"UTC"}:{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});}
  function openFile(file:DealAttachment){onthread(file.threadId,file.messageId);}
</script>
<section class="company-overview" aria-label={t("fork.deals.company_overview",{name:company})}>
  <h2>{company}</h2><p class="scope">{t("fork.deals.local_scope")}</p>
  {#if error}<p class="error" role="alert">{error}<button onclick={()=>void load(company)}>{t("fork.deals.retry")}</button></p>{/if}
  {#if loading && !context}<p role="status">{t("fork.deals.loading")}</p>{/if}
  {#if context}
    {#if context.pinned}<div class="pinned"><span class="microlabel">{t("fork.deals.current_document")}</span><button class="pinned-file" onclick={()=>openFile(context!.pinned!)}>{context.pinned.filename}</button><button class="quiet" disabled={saving} onclick={()=>void save(null,false)}>{t("fork.deals.unpin")}</button></div>{/if}
    <details class="notes"><summary>{t("fork.deals.private_notes")}{#if context.notes}<span class="has-notes" aria-hidden="true"></span>{/if}</summary><p class="scope">{t("fork.deals.notes_local")}</p><textarea bind:value={notes} oninput={e=>dealsStore.setNoteDraft(company,e.currentTarget.value)} maxlength="20000" rows="4" aria-label={t("fork.deals.private_notes")}></textarea><div class="note-actions">{#if saved && !dirty}<span role="status">{t("fork.deals.settings_saved")}</span>{/if}<button disabled={!dirty||saving} onclick={()=>{notes=context!.notes;dealsStore.clearNoteDraft(company);saved=false;}}>{t("fork.deals.cancel")}</button><button class="save" disabled={!dirty||saving} onclick={()=>void save(context!.pinned?.id??null,true)}>{t("fork.deals.save_notes")}</button></div></details>
    <div class="tabs" role="group" aria-label={t("fork.deals.overview")}><button class:active={tab==='conversations'} aria-pressed={tab==='conversations'} onclick={()=>tab='conversations'}>{t("fork.deals.conversations",{n:context.conversationCount})}</button><button class:active={tab==='people'} aria-pressed={tab==='people'} onclick={()=>tab='people'}>{t("fork.deals.people")}</button><button class:active={tab==='files'} aria-pressed={tab==='files'} onclick={()=>tab='files'}>{t("fork.deals.attachments")}</button><button class:active={tab==='meetings'} aria-pressed={tab==='meetings'} onclick={()=>tab='meetings'}>{t("fork.deals.meetings")}</button></div>
    <div class="content">
      {#if tab==='conversations'}{#each context.conversations as row}<button class="item" onclick={()=>onthread(row.id)}><strong>{row.subject}</strong><span>{row.fromName} &middot; {when(row.date)}</span></button>{:else}<p>{t("fork.deals.no_conversations")}</p>{/each}
      {:else if tab==='people'}{#each context.people as person}<button class="item" onclick={()=>onsearch(`from:"${person.addr}"`)}><strong>{person.name||person.addr}</strong>{#if person.name}<span>{person.addr}</span>{/if}</button>{:else}<p>{t("fork.deals.no_people")}</p>{/each}
      {:else if tab==='files'}
        {#if context.attachments.length}<AttachmentChips attachments={context.attachments} onsource={file=>{const source=context?.attachments.find(a=>a.id===file.id);if(source)onthread(source.threadId,source.messageId);}} />
        <label class="pin-select">{t("fork.deals.current_document")}<select aria-label={t("fork.deals.current_document")} value={context.pinned?.id??""} disabled={saving} onchange={e=>void save(e.currentTarget.value?Number(e.currentTarget.value):null,false)}><option value="">{t("fork.deals.no_current_document")}</option>{#each context.attachments as file}<option value={file.id}>{file.filename}</option>{/each}</select></label>
        {:else}<p>{t("fork.deals.no_attachments")}</p>{/if}
      {:else}{#each context.meetings as event}<button class="item" onclick={()=>onevent(event.id,event.startTs)}><strong>{event.summary}</strong><span>{when(event.startTs,event.allDay)}</span></button>{:else}<p>{t("fork.deals.no_meetings")}</p>{/each}{/if}
    </div>
    <p class="scope limits">{t("fork.deals.overview_limits")}</p>
  {/if}
</section>
<style>
 .company-overview{max-height:60vh;overflow:auto;padding-top:14px}.company-overview h2{font-size:16px;margin:0 0 5px;color:var(--deal-ink)}p{font-size:12px;line-height:1.5;color:var(--text-dim);margin:6px 0}.scope{font-size:11px}.tabs{display:flex;gap:3px;flex-wrap:wrap;margin-top:12px;border-bottom:1px solid var(--hairline);padding-bottom:8px}.tabs button{font-size:11px;padding:5px 7px;border-radius:var(--radius-s);color:var(--text-dim)}.tabs .active{background:var(--deal-soft);color:var(--deal-ink);box-shadow:inset 0 -2px var(--deal-ink)}.item{display:flex;flex-direction:column;align-items:flex-start;text-align:left;gap:4px;width:100%;border:0;border-radius:0;border-bottom:1px solid var(--hairline);padding:9px 0;overflow-wrap:anywhere;min-width:0}.item strong{font-size:12px;font-weight:500}.item span{font-size:11px;color:var(--text-dim)}button:hover:not(:disabled){background:var(--hover)}button:disabled{opacity:.5}.pin-select{display:flex;flex-direction:column;gap:6px;font-size:12px;margin-top:14px;color:var(--text-dim)}.pin-select select{max-width:100%;padding:6px;border:1px solid var(--hairline-strong);border-radius:var(--radius-s);color:var(--text);background:var(--surface)}.quiet{font-size:11px;color:var(--deal-ink);padding:5px;flex-shrink:0}.notes{margin-top:12px;padding:10px;background:var(--surface);border:1px solid var(--hairline);border-radius:var(--radius-s)}summary{font-size:12px;font-weight:500;cursor:pointer}.has-notes{display:inline-block;width:5px;height:5px;margin-left:6px;border-radius:50%;background:var(--deal-ink)}textarea{box-sizing:border-box;width:100%;padding:8px;border:1px solid var(--hairline-strong);border-radius:var(--radius-s);background:var(--surface);color:var(--text);resize:vertical;font-size:12px;line-height:1.5}.note-actions{display:flex;justify-content:flex-end;align-items:center;gap:6px;margin-top:6px}.note-actions button{font-size:11px;border:1px solid var(--hairline-strong);border-radius:var(--radius-s);padding:5px 8px}.note-actions span{font-size:11px;color:var(--text-dim);margin-right:auto}.note-actions .save{background:var(--primary);color:var(--on-primary)}.pinned{display:flex;flex-direction:column;gap:5px;padding:10px;margin-top:10px;background:var(--deal-soft);border-left:2px solid var(--deal-ink)}.pinned .microlabel{color:var(--deal-ink);font-size:10px}.pinned-file{text-align:left;overflow-wrap:anywhere;font-size:12px;font-weight:600}.pinned .quiet{align-self:flex-start;padding:0}.limits{margin-top:12px}.error{color:var(--danger)}button:focus-visible,summary:focus-visible,textarea:focus-visible{outline:2px solid var(--focus);outline-offset:2px}
</style>
