<script lang="ts">
  import {t} from "../../lib/i18n/index.svelte";
  import {onMount} from "svelte";
  import {api,errorMessage} from "../../lib/api";
  import {parseSnippets,addSnippet,type ComposeSnippet} from "./workflow";
  let {oninsert,currentText}:{oninsert:(text:string)=>void;currentText:string}=$props();
  let open=$state(false),items=$state<ComposeSnippet[]>([]),name=$state(""),text=$state(""),error=$state(""),ready=$state(false),busy=$state(false);
  onMount(()=>{void api.getSettings().then(s=>{items=parseSnippets(s.fork_compose_snippets);ready=true;}).catch(e=>{error=errorMessage(e);});});
  async function persist(next:ComposeSnippet[]){busy=true;error="";try{await api.setSetting("fork_compose_snippets",JSON.stringify(next));items=next;name="";text="";}catch(e){error=errorMessage(e);}finally{busy=false;}}
  function save(){try{void persist(addSnippet(items,name,text));}catch(e){error=errorMessage(e);}}
</script>
<div class="snippets"><button class="toggle" aria-expanded={open} onclick={()=>open=!open}>{t("fork.snippets.toggle")}</button>{#if open}<section aria-label={t("fork.snippets.region")}><header><strong>{t("fork.snippets.title")}</strong><button onclick={()=>open=false} aria-label={t("fork.snippets.close")}>×</button></header>{#each items as item}<div class="item"><button class="insert" title={item.text} onclick={()=>{oninsert(item.text);open=false;}}>{item.name}<small>{item.text.slice(0,85)}</small></button><button disabled={busy} onclick={()=>void persist(items.filter(s=>s!==item))} aria-label={t("fork.snippets.delete",{name:item.name})}>×</button></div>{/each}<label>{t("fork.snippets.name")}<input bind:value={name} maxlength="80"/></label><label>{t("fork.snippets.text")}<textarea bind:value={text} rows="4" maxlength="12000"></textarea></label><div class="actions"><button onclick={()=>text=currentText}>{t("fork.snippets.use_current")}</button><button disabled={!ready||busy||!name.trim()||!text.trim()} onclick={save}>{t("fork.snippets.save")}</button></div>{#if error}<p role="alert">{error}</p>{/if}</section>{/if}</div>
<style>.snippets{position:relative}.toggle{font-size:12px;padding:8px}section{position:absolute;z-index:50;bottom:40px;left:0;width:min(360px,75vw);max-height:65vh;overflow:auto;padding:15px;background:var(--surface-raised);border:1px solid var(--hairline-strong);border-radius:var(--radius-m);box-shadow:0 12px 40px #0004}header,.item,.actions{display:flex;gap:10px;align-items:center;justify-content:space-between}header{margin-bottom:10px}.item{border-bottom:1px solid var(--hairline);padding:8px 0}.insert{flex:1;text-align:left;font-size:13px}small{display:block;color:var(--text-dim);font-size:11px;margin-top:3px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;max-width:280px}label{display:block;font-size:12px;color:var(--text-dim);margin-top:12px}input,textarea{box-sizing:border-box;width:100%;padding:8px;margin-top:4px;background:var(--surface);border:1px solid var(--hairline-strong);border-radius:var(--radius-s);font-size:13px;resize:vertical}.actions{margin-top:10px}.actions button{font-size:12px;color:var(--primary)}p{color:var(--danger);font-size:12px}</style>
