import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
execSync('npm run demo:build', {stdio:'pipe', windowsHide:true});
const out = 'docs/fork/shots/1.1.4';
const capture = process.env.SKIM_CAPTURE === '1';
mkdirSync(out, { recursive: true });
const browser = await chromium.launch();
try {
 for (const theme of ['base-dark', 'base-light']) {
  const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, timezoneId: 'Africa/Johannesburg' });
  await context.addInitScript(theme => {
   localStorage.setItem('skimdemo.theme', theme);
   localStorage.setItem('skimdemo.fork_thread_multi', '1');
   localStorage.setItem('skimdemo.fork_court_nudge', 'off');
  }, theme);
  // A deterministic image checks loading; companies in the demo are fictional.
  await context.route('https://www.google.com/s2/favicons**', route => route.request().url().includes('acme-partners') ? route.abort() : route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><rect width="64" height="64" rx="8" fill="#3165cd"/><path d="M16 48V16l32 32V16" stroke="white" stroke-width="6" fill="none"/></svg>' }));
  const page = await context.newPage(); page.setDefaultTimeout(10000);
  const errors=[]; page.on('pageerror', e => errors.push(String(e)));
  await page.goto('http://127.0.0.1:1421/');
  await page.locator('.row', { hasText: 'Q3 launch' }).first().waitFor();
  await page.evaluate(() => document.fonts.ready);
  const nav = await page.locator('.sidebar .item .name').allTextContents();
  assert.deepEqual(nav.slice(0,3), ['Inbox','Calendar','Deals']);
  await page.locator('.sidebar .item', {hasText:'Deals'}).click();
  await page.locator('.deal-badge img.loaded').first().waitFor();
  assert.ok(await page.locator('.deal-badge .initials').count());
  if (capture) await page.screenshot({path:`${out}/deals-${theme}.png`});
  await page.locator('.row', {hasText:'Q3 launch'}).first().click();
  await page.locator('.history-label').waitFor();
  assert.equal(await page.locator('.convo .message').count(), 1);
  if (capture) await page.screenshot({path:`${out}/thread-${theme}.png`});
  await page.locator('.chat-row').first().click();
  await page.locator('.reply-target .message').waitFor();
  await page.waitForFunction(() => document.querySelector('.reply-target iframe')?.contentDocument?.body?.textContent?.trim().length > 0);
  await page.locator('.reply-target iframe').evaluate(async el => {
   await el.contentDocument.fonts.ready;
   await new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
  });
  if (capture) await page.screenshot({path:`${out}/thread-history-${theme}.png`});
  await page.getByRole('button', {name:'Collapse all',exact:true}).click();
  assert.equal(await page.locator('.convo .message').count(), 0);
  await page.locator('.chat-row').first().click();
  await page.locator('.convo .reply-target .message').waitFor();
  await page.locator('.sidebar .item.calendar').click();
  await page.locator('.fork-cal .new').click();
  const panel = page.locator('.fork-cal .panel');
  await panel.locator('.title').fill('Planning session');
  await panel.getByRole('combobox', {name:'Repeat',exact:true}).selectOption('custom');
  await panel.getByLabel('Repeat every', {exact:true}).fill('2');
  await panel.getByRole('combobox', {name:'Frequency',exact:true}).selectOption('WEEKLY');
  await panel.getByRole('button', {name:'Mon',exact:true}).click();
  await panel.getByRole('combobox', {name:'Ends',exact:true}).last().selectOption('count');
  await panel.getByLabel('Occurrences', {exact:true}).fill('8');
  await panel.getByLabel('Use calendar defaults').uncheck();
  await panel.getByLabel('Reminder method').selectOption('email');
  await panel.getByLabel('minutes before', {exact:true}).fill('45');
  await panel.getByRole('combobox', {name:'Show as',exact:true}).selectOption('transparent');
  await panel.getByRole('combobox', {name:'Visibility',exact:true}).selectOption('private');
  await panel.getByRole('button', {name:'Sage',exact:true}).click();
  await panel.getByLabel('Modify the event', {exact:true}).check();
  await panel.getByLabel('Time zone', {exact:true}).fill('Europe/London');
  await panel.getByLabel('Time zone', {exact:true}).press('Tab');
  await panel.locator('.body').evaluate(el => { el.scrollTop=0; });
  if (capture) await page.screenshot({path:`${out}/editor-${theme}.png`});
  await panel.getByText('Event settings', {exact:true}).scrollIntoViewIfNeeded();
  if (capture) await page.screenshot({path:`${out}/editor-options-${theme}.png`});
  await panel.getByRole('button', {name:'Create',exact:true}).click();
  await panel.waitFor({state:'detached'}).catch(async e => { console.log(await panel.innerText()); throw e; });
  await page.locator('.ec-event', {hasText:'Planning session'}).first().click();
  await page.getByRole('button', {name:'Edit event',exact:true}).click();
  await panel.waitFor();
  assert.equal(await panel.getByRole('combobox', {name:'Visibility',exact:true}).inputValue(), 'private');
  assert.equal(await panel.getByRole('combobox', {name:'Show as',exact:true}).inputValue(), 'transparent');
  assert.equal(await panel.getByLabel('minutes before', {exact:true}).inputValue(), '45');
  assert.equal(await panel.getByRole('button', {name:'Sage',exact:true}).getAttribute('aria-pressed'), 'true');
  assert.equal(await panel.getByLabel('Modify the event', {exact:true}).isChecked(), true);
  assert.equal(await panel.getByLabel('Time zone', {exact:true}).inputValue(), 'Europe/London');
  assert.match(await panel.locator('.rule').textContent(), /Every 2.*8 occurrences/);
  await panel.getByRole('button', {name:'Close',exact:true}).click();
  await page.locator('.ec-event', {hasText:'Board prep'}).first().click();
  await page.getByRole('button', {name:'Edit event',exact:true}).click();
  await panel.getByLabel('Apply changes to', {exact:true}).selectOption('series');
  await page.waitForFunction(() => document.querySelector('#event-scope')?.value === 'series');
  assert.match(await panel.locator('.rule').textContent(), /Weekly/);
  if (capture) await page.screenshot({path:`${out}/series-${theme}.png`});
  await page.setViewportSize({width:1200,height:800});
  await panel.getByText('Guests can',{exact:true}).scrollIntoViewIfNeeded();
  assert.equal(await panel.evaluate(e=>e.scrollWidth <= e.clientWidth),true);
  assert.equal(await panel.getByRole('button',{name:'Save',exact:true}).isVisible(),true);
  if (capture) await page.screenshot({path:`${out}/editor-1200-${theme}.png`});
  assert.deepEqual(errors, []);
  console.log(`${theme}: nav, logos, thread history, editor save/reopen and series scope passed`);
  await context.close();
 }
} finally { await browser.close(); }
