import { chromium } from "playwright";
import assert from "node:assert/strict";
import { mkdirSync } from "node:fs";
import { execSync } from "node:child_process";
execSync("npm run demo:build", { stdio: "pipe", windowsHide: true });
const capture = process.env.SKIM_CAPTURE === "1";
const out = "docs/fork/shots/1.1.5";
if (capture) mkdirSync(out, { recursive: true });
const browser = await chromium.launch();
try {
 for (const theme of ["base-dark", "base-light"]) {
  const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, timezoneId: "Africa/Johannesburg" });
  await context.addInitScript(theme => {
   localStorage.setItem("skimdemo.theme", theme);
   localStorage.setItem("skimdemo.fork_thread_multi", "1");
   localStorage.setItem("skimdemo.fork_court_nudge", "off");
  }, theme);
  await context.route("https://www.google.com/s2/favicons**", route => route.fulfill({ contentType: "image/svg+xml", body: '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><rect width="64" height="64" rx="8" fill="#3165cd"/><path d="M16 48V16l32 32V16" stroke="white" stroke-width="6" fill="none"/></svg>' }));
  const page = await context.newPage(); page.setDefaultTimeout(10000);
  const errors = []; page.on("pageerror", e => errors.push(String(e)));
  await page.goto("http://127.0.0.1:1421/");
  await page.locator(".row", { hasText: "Q3 launch" }).first().click();
  await page.locator(".convo .message").waitFor();
  await page.evaluate(() => document.fonts.ready);
  const resize = page.getByRole("slider", { name: "Resize message list" });
  const before = Number(await resize.getAttribute("aria-valuenow"));
  await resize.focus(); await resize.press("ArrowRight");
  assert.equal(Number(await resize.getAttribute("aria-valuenow")), before + 20);
  await resize.press("ArrowLeft");
  assert.equal(Number(await resize.getAttribute("aria-valuenow")), before);
  await page.getByRole("button", { name: "Search conversation", exact: true }).click();
  await page.getByRole("searchbox", { name: "Search conversation" }).fill("Friday please");
  assert.equal(await page.locator(".conversation-tools .result").count(), 1);
  await page.locator(".conversation-tools .result").click();
  assert.equal(await page.locator(".reply-target [data-message-id]").getAttribute("data-message-id"), "1009");
  await page.getByRole("button", { name: "Files", exact: true }).click();
  await page.getByRole("button", { name: "Load remaining messages", exact: true }).click();
  await page.getByText("3 of 3 message bodies loaded.", { exact: false }).waitFor();
  assert.equal(await page.getByRole("button", { name: "Load remaining messages", exact: true }).count(), 0);
  assert.ok((await page.locator(".conversation-tools").innerText()).includes("loaded"));
  assert.equal(await page.locator(".conversation-tools .file-group .chip").count(), 2);
  assert.match(await page.locator(".conversation-tools").innerText(), /launch-checklist.pdf/);
  await page.getByRole("button", { name: "Files", exact: true }).click();
  await page.getByRole("button", { name: "Expand all", exact: true }).click();
  assert.equal(await page.locator(".convo .message").count(), 3);
  assert.equal(await page.locator(".reply-target .message").count(), 1);
  await page.getByRole("button", { name: "Collapse all", exact: true }).click();
  assert.equal(await page.locator(".convo .message").count(), 0);
  await page.locator(".chat-row").last().click();
  const targetId = await page.locator(".reply-target [data-message-id]").getAttribute("data-message-id");
  await page.locator(".primary-reply").click();
  await page.locator(".inline-reply").waitFor();
  await page.getByRole("button", { name: "Collapse all", exact: true }).click();
  assert.equal(await page.locator(".inline-reply").count(), 1);
  assert.equal(await page.locator(".inline-reply").locator("..").locator("[data-message-id]").getAttribute("data-message-id"), targetId);
  // Close the fixture composer through its own Escape handler; no send occurs.
  await page.locator(".inline-reply [contenteditable=true]").first().press("Escape");
  await page.locator(".inline-reply").waitFor({ state: "detached" });
  await page.getByRole("button", { name: "Collapse all", exact: true }).click();
  await page.locator(".chat-row").first().click();
  await page.locator(".pane .scroll").evaluate(el => { el.scrollTop = 0; });
  for (const width of [1600, 1200, 900]) {
   await page.setViewportSize({ width, height: width === 1600 ? 1000 : 800 });
   await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
   assert.equal(await page.locator(".pane").evaluate(el => el.scrollWidth <= el.clientWidth), true, `reading overflow at ${width}px`);
   if (capture) await page.screenshot({ path: `${out}/inbox-${width}-${theme}.png` });
  }
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.locator(".sidebar .item", { hasText: "Deals" }).click();
  await page.locator(".deal-tools").getByLabel("Company", { exact: true }).selectOption("Northwind");
  await page.locator(".deal-tools").getByRole("button", { name: "Overview", exact: true }).click();
  await page.locator(".deal-tools .overview").waitFor();
  assert.match(await page.locator(".deal-tools .overview").innerText(), /Northwind/);
  if (capture) await page.screenshot({ path: `${out}/deals-${theme}.png` });
  await page.locator(".sidebar .item", { hasText: "Inbox" }).click();
  await page.getByRole("button", { name: "Search & filters", exact: true }).click();
  await page.locator(".search-tools").getByLabel("Sender", { exact: true }).fill("anna@northwind.example");
  await page.getByLabel("Name this search", { exact: true }).fill("Anna follow-up");
  await page.getByRole("button", { name: "Save search", exact: true }).click();
  await page.getByRole("button", { name: "Anna follow-up", exact: true }).waitFor();
  await page.getByRole("button", { name: "Search & filters", exact: true }).click();
  await page.locator(".sidebar .item.calendar").click();
  await page.getByRole("radio", { name: "Workweek", exact: true }).click();
  assert.equal(await page.getByRole("radio", { name: "Workweek", exact: true }).getAttribute("aria-checked"), "true");
  await page.getByLabel("Visible hours start", { exact: true }).selectOption("08:00");
  await page.getByLabel("Visible hours end", { exact: true }).selectOption("19:00");
  await page.getByRole("button", { name: "Choose a date", exact: true }).click();
  assert.equal(await page.locator(".mini-month .days button").count(), 42);
  await page.getByRole("button", { name: "Choose a date", exact: true }).click();
  await page.locator(".calendar-controls .control").click();
  await page.locator(".calendar-filters").getByLabel("Team", { exact: true }).uncheck();
  await page.waitForFunction(() => ![...document.querySelectorAll('.ec-event')].some(el => el.textContent.includes('Offsite')));
  await page.locator(".calendar-filters").getByLabel("Team", { exact: true }).check();
  await page.locator(".calendar-controls .control").click();
  await page.locator(".ec-event", { hasText: "Q3 launch sync" }).first().click();
  await page.getByRole("complementary", { name: "Event preview", exact: true }).waitFor();
  assert.equal(await page.locator(".fork-cal .panel").count(), 0);
  assert.equal(await page.getByRole("button", { name: /Discard.*change/ }).count(), 0);
  if (capture) await page.screenshot({ path: `${out}/calendar-preview-${theme}.png` });
  await page.getByRole("button", { name: "Duplicate", exact: true }).click();
  const panel = page.locator(".fork-cal .panel");
  assert.equal(await panel.locator("textarea.title").inputValue(), "Q3 launch sync");
  assert.equal(await panel.getByRole("combobox", { name: "Repeat", exact: true }).inputValue(), "none");
  assert.equal(await panel.getByRole("button", { name: "Create", exact: true }).count(), 1);
  await panel.getByRole("button", { name: "Find a time", exact: true }).click();
  await panel.getByText("Availability unavailable for these guests", { exact: true }).waitFor();
  assert.match(await panel.locator(".unknown").innerText(), /marcus@acme-partners.example/);
  assert.match(await panel.locator(".finder").innerText(), /Available for calendars we can check|No available slots/);
  if (capture) await page.screenshot({ path: `${out}/calendar-find-time-${theme}.png` });
  await panel.getByRole("button", { name: "Close", exact: true }).click();
  await page.locator(".ec-event", { hasText: "Board prep" }).first().click();
  await page.getByRole("button", { name: "Edit event", exact: true }).click();
  await panel.getByLabel("Apply changes to", { exact: true }).selectOption("following");
  await page.waitForFunction(() => document.querySelector('#event-scope')?.value === 'following');
  assert.equal(await panel.getByRole("button", { name: "Delete", exact: true }).count(), 0);
  for (const width of [1600, 1200, 900]) {
   await page.setViewportSize({ width, height: width === 1600 ? 1000 : 800 });
   await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
   assert.equal(await panel.evaluate(el => el.scrollWidth <= el.clientWidth), true);
   assert.equal(await panel.getByRole("button", { name: "Save", exact: true }).isVisible(), true);
   if (capture) await page.screenshot({ path: `${out}/calendar-editor-${width}-${theme}.png` });
  }
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.locator(".sidebar .item", { hasText: "Inbox" }).click();
  await resize.focus(); await resize.press("ArrowRight");
  const savedWidth = Number(await resize.getAttribute("aria-valuenow"));
  await page.reload();
  await resize.waitFor();
  assert.equal(Number(await resize.getAttribute("aria-valuenow")), savedWidth);
  await page.getByRole("button", { name: "Search & filters", exact: true }).click();
  await page.getByRole("button", { name: "Anna follow-up", exact: true }).waitFor();
  await page.locator(".sidebar .item.calendar").click();
  assert.equal(await page.getByLabel("Visible hours start", { exact: true }).inputValue(), "08:00");
  assert.equal(await page.getByLabel("Visible hours end", { exact: true }).inputValue(), "19:00");
  assert.deepEqual(errors, []);
  console.log(`${theme}: reading search, files, expand/collapse, draft target, resizer, Deals, saved search, calendar controls, preview, duplicate, unknown availability and following scope passed`);
  await context.close();
 }
} finally { await browser.close(); }
